# Netlify configuration for React SPA
[build]
  # Build command
  command = "npm run build"
  # Publish directory (output of build)
  publish = "build"

# SPA redirect rules - serve index.html for all routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Optional: Environment variables (if needed in the future)
# [build.environment]
#   NODE_VERSION = "18"

# Optional: Headers for security and caching
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
